{"issue":{"title":"[CF 1080] Error when I start my client ","body":" <p>IMPORTANT: If your issue is only occurring with a specific icon, include an export string of the icon in this ticket. Similarly, if the issue involves an entire group or an entire profile, include the entire export string of the group or profile.</p><p>To get an export string, open the icon editor, and click button labeled \"Import/Export/Backup\". Select the \"To string\" option for the appropriate export type for your issue, and then press CTRL+C to copy it to your clipboard.</p><p>What steps will reproduce the problem?<br>1. deactivate all addons except tellmewhen<br>2. before launching the client clear the cache folder<br>3. start client</p><p>What do you expect to happen? What happens instead?</p><p>I do not want to see the error</p><p>What version of TellMeWhen are you using? (\"The latest\" is not a version)</p><p>7.2.3-2-ga288992</p><p>Do you have an error log of what happened?<br>Message: ...dOns\\TellMeWhen\\Components\\Core\\Spells\\ItemCache.lua:110: bad argument #1 to 'pairs' (table expected, got nil)<br>Time: 01/23/15 08:44:33<br>Count: 1<br>Stack: [C]: in function `pairs'<br>...dOns\\TellMeWhen\\Components\\Core\\Spells\\ItemCache.lua:110: in function &lt;...dOns\\TellMeWhen\\Components\\Core\\Spells\\ItemCache.lua:94&gt;<br>(tail call): ?<br>[C]: ?<br>[string \"safecall Dispatcher[1]\"]:9: in function &lt;[string \"safecall Dispatcher[1]\"]:5&gt;<br>(tail call): ?<br>Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:1611: in function `Fire'<br>...ace\\AddOns\\TellMeWhen\\Options\\TellMeWhen_Options.lua:508: in function &lt;...ace\\AddOns\\TellMeWhen\\Options\\TellMeWhen_Options.lua:416&gt;<br>(tail call): ?<br>[C]: ?<br>[string \"safecall Dispatcher[1]\"]:9: in function &lt;[string \"safecall Dispatcher[1]\"]:5&gt;<br>(tail call): ?<br>...<br>Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:1611: in function `Fire'<br>Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:3191: in function `UpdateNormally'<br>Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:3341: in function `Update'<br>Interface\\AddOns\\TellMeWhen\\TellMeWhen.lua:1861: in function `?'<br>...When\\Lib\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:145: in function &lt;...When\\Lib\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:145&gt;<br>[string \"safecall Dispatcher[1]\"]:4: in function &lt;[string \"safecall Dispatcher[1]\"]:4&gt;<br>[C]: ?<br>[string \"safecall Dispatcher[1]\"]:13: in function `?'<br>...When\\Lib\\CallbackHandler-1.0\\CallbackHandler-1.0.lua:90: in function `Fire'<br>...\\AddOns\\TellMeWhen\\Lib\\AceEvent-3.0\\AceEvent-3.0.lua:120: in function &lt;...\\AddOns\\TellMeWhen\\Lib\\AceEvent-3.0\\AceEvent-3.0.lua:119&gt;</p><p>Locals: &lt;none&gt;</p><p>Please provide any additional information below (including any export strings if applicable; see above.)</p><p>I did clear my cache and disabled all addons except tellmewhen, the error is still there and it is there every time I start the client.</p><p>best regards<br>Paul</p> \n<br>\n\n> Posted by CurseForge user <a href=\"https://wow.curseforge.com/members/pvanovertveld\">pvanovertveld</a> | Imported from CurseForge issue <a href=\"https://wow.curseforge.com/projects/tellmewhen/issues/1080\">#1080</a> | <a href=\"https://github.com/tmw-issue-import/dump/blob/master/html/1080.html\">Raw</a>","closed":true,"closed_at":"2015-01-24T03:21:42Z","created_at":"2015-01-23T11:19:10Z","updated_at":"2015-01-24T03:21:42Z","labels":["defect","resolved"]},"comments":[{"body":" <p>Fixed in gdca660c.</p> <div class=\"project-issue-comment-body-modified\"> </div> \n<br>\n\n> Posted by CurseForge user <a href=\"https://wow.curseforge.com/members/Cybeloras\">Cybeloras</a>","created_at":"2015-01-24T03:21:34Z"}]}